# Generated by Django 5.0.1 on 2024-01-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('slug', models.SlugField()),
                ('img_url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
