# Generated by Django 5.0.1 on 2024-02-22 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dt_nascimento', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('dt_publicacao', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='imagens/')),
                ('titulo', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-dt_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='HelloBlog.publicacao')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
