# Generated by Django 5.0.1 on 2024-02-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0002_alter_comentario_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-dt_comentario']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='publicado_em',
            new_name='dt_comentario',
        ),
    ]
