# Generated by Django 5.0.2 on 2024-02-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloBlog', '0004_alter_publicacao_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
